# Generated by Django 5.2.1 on 2025-09-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_alter_product_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='p_id',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.size'),
            preserve_default=False,
        ),
    ]
