# Generated by Django 5.2.1 on 2025-09-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0028_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
