# Generated by Django 5.2.1 on 2025-10-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0031_order_payment_id_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guarentee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
