# Generated by Django 5.2.7 on 2025-10-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0032_remove_product_guarentee_remove_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category_diff',
            field=models.CharField(choices=[('jewelry', 'jewelry'), ('cosmetic', 'coesmetic'), ('skincare', 'skincare')], default='non', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
