# Generated by Django 5.2.7 on 2025-10-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0036_coupon_orderotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderotp',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.order'),
        ),
    ]
