# Generated by Django 5.2.7 on 2025-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0040_userprofile_first_name_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
