# Generated by Django 5.2.7 on 2025-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0041_userprofile_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
    ]
