# Generated by Django 5.2.7 on 2025-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0042_offerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='where_to_display',
            field=models.CharField(choices=[('none', 'None'), ('home', 'Home')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='angels', max_length=100),
        ),
    ]
