# Generated by Django 5.2.7 on 2025-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0043_alter_product_where_to_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='angels', max_length=100),
        ),
    ]
